# Site settings
title: claytantor - I am a doer not a beer.
description: "This is were I talk about github related projects and contributions."
baseurl: "/claytantor.github.io" # the subpath of your site
url: "http://claytantor.github.io"

# User settings
username: claytantor
user_title: claytantor - I am a doer not a beer.
email: claytantor@gmail.com
twitter_username: claytantor
github_username:  claytantor
gplus_username:  claytantor


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: blueweave
    url: https://github.com/claytantor/blueweave
  - name: jetty-jersey-spring-bootstrap
    url: https://github.com/claytantor/jetty-jersey-spring-bootstrap
  - name: coinbase4py
    url: https://github.com/claytantor/coinbase4py
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor']
